//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Visitors = new HashSet<Visitors>();
        }
    
        public int RequestID { get; set; }
        public string RequestType { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime RequestStartDate { get; set; }
        public System.DateTime RequestEndDate { get; set; }
        public string RequestPurpouse { get; set; }
        public int EmployeID { get; set; }
        public string RequestStatus { get; set; }
        public string RequestDescription { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        [JsonIgnore]
        public virtual Employes Employes { get; set; }
        [JsonIgnore]
        public virtual Groups Groups { get; set; }
        
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visitors> Visitors { get; set; }
    }
}
