//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Visitors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visitors()
        {
            this.Requests = new HashSet<Requests>();
        }

        public int VisitorID { get; set; }
        public string VisitorSurname { get; set; }
        public string VisitorName { get; set; }
        public string VisitorPatronymic { get; set; }
        public string VisitorPhone { get; set; }
        public string VisitorEmail { get; set; }
        public string VisitorLogin { get; set; }
        public string VisitorPassword { get; set; }
        public string VisitorOrganisation { get; set; }
        public Nullable<System.DateTime> VisitorDateOfBirth { get; set; }
        public string VisitorDescription { get; set; }
        public string VisitorSeriaPassport { get; set; }
        public string VisitorNumberPassport { get; set; }
        public byte[] VisitorPhoto { get; set; }
        public string VisitorSkan { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
